<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE solarSystem [
 <!ELEMENT solarSystem (body*)>
 <!ELEMENT body (planet|satellite|asteroid)> <!--Corregido: <!ELEMENT body (planet,satellite,asteroid)> -->
 <!ELEMENT planet (#PCDATA)>
 <!ELEMENT satellite (#PCDATA)>
 <!ELEMENT asteroid (#PCDATA)>
]>
<solarSystem>
 <body>
 <planet>Earth</planet>
 <satellite>Moon</satellite>
 <!--Corregido: <asteroid>Ceres</asteroid> -->
 </body>
 <asteroid>Ceres</asteroid> <!--Corregido: borrado (movido a linea 13) -->
</solarSystem>