<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE writers [
 <!ELEMENT writers (writer*)>
 <!ELEMENT writer (name, birth)>
 <!ELEMENT name (#PCDATA)>
 <!ELEMENT birth (#PCDATA)>
]>
<writers>
 <writer>
 <name>Mario Vargas Llosa</name>
 <birth>March 28th 1936</birth>
 </writer>
 <writer>
 <birth>April 1st 1929</birth><!--Corregido:  <name>Milan Kunfromra</name>-->
 <name>Milan Kunfromra</name><!--Corregido:  <birth>April 1st 1929</birth>-->
 </writer>
</writers>
