=== alvaromartinsalazar/LenguajedeMarcas/TEMA_1_INTRODUCCION_A_LOS_LENGUAJES_DE_MARCAS. XML/Martin_Salazar_Alvaro_LM_U1_T2/Ejercicio_2/ej2.dtd
<!ELEMENT Libro (Titulo,Seccion,Contenido,Copyright)>
<!ATTLIST Libro Catalogo NMTOKEN #REQUIRED>
<!ELEMENT Titulo (#PCDATA)>
<!ELEMENT Seccion (#PCDATA)>
<!ELEMENT Contenido (Capitulo,Separacion)>
<!ELEMENT Capitulo (Tema)>
<!ATTLIST Capitulo materia NMTOKEN #REQUIRED>
<!ELEMENT Tema (#PCDATA)>
<!ELEMENT Separacion EMPTY>
<!ELEMENT Copyright (#PCDATA)>

=== alvaromartinsalazar/LenguajedeMarcas/TEMA_1_INTRODUCCION_A_LOS_LENGUAJES_DE_MARCAS. XML/Martin_Salazar_Alvaro_LM_U1_T2/Ejercicio_2/ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Libro SYSTEM "ej2.dtd">
<Libro Catalogo="manolo">
    <Titulo>Manolo</Titulo>
    <Seccion>2</Seccion>
    <Contenido>
        <Capitulo materia="XML">
            <Tema>4</Tema>
        </Capitulo>
        <Separacion></Separacion>
    </Contenido>
    <Copyright>si</Copyright>
</Libro>
